[build]
  command = "npm run build"
  publish = "dist"

# Optional: avoid accidentally disabling the camera with site-wide headers.
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self)"
